scriptencoding utf-8
set encoding=utf-8

" Vundle
set nocompatible
filetype plugin indent on
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" Vundle Plug-ins
Plugin 'Valloric/YouCompleteMe'     " Completion
Plugin 'tpope/vim-sleuth'           " Auto indent
Plugin 'scrooloose/nerdcommenter'   " Comment helper
Plugin 'scrooloose/nerdtree'        " File browser
Plugin 'jlanzarotta/bufexplorer'    " File browser
Plugin 'scrooloose/syntastic'       " Syntax check
Plugin 'bling/vim-airline'          " Airline
Plugin 'tpope/vim-fugitive'         " Git support
Plugin 'airblade/vim-gitgutter'     " Git gutter
Plugin 'rking/ag.vim'               " Searching
Plugin 'https://github.com/kien/ctrlp.vim' " Fuzzy file finding
Plugin 'Lokaltog/vim-easymotion'

" Language, Framework specific
Plugin 'klen/python-mode'
Plugin 'vim-perl/vim-perl'
Plugin 'vim-ruby/vim-ruby'
Plugin 'burnettk/vim-angular'
Plugin 'https://github.com/othree/javascript-libraries-syntax.vim'

call vundle#end()         " required
filetype plugin indent on " required
set scrolloff=15

set number
set relativenumber

" Color settings
set t_Co=256
let g:rehash256=1

" Allow mouse control
set mouse=a

" Color Scheme
set background=dark

" Highlight current line
set cursorline
hi CursorLine cterm=NONE ctermbg=238
highlight LineNr ctermfg=7

" Color column
set colorcolumn=100
highlight ColorColumn ctermbg=0

" Italicize comments
highlight Comment cterm=italic

" Set automatic indentation
set autoindent
set smartindent
set expandtab

" Set tabs at 4 spaces
set cindent
set tabstop=4
set shiftwidth=4
set sw=4
set notextmode
set notextauto
set hlsearch
set incsearch

" Reload vimrc
nmap <silent> <leader>V :source ~/.vimrc/<cr>:filetype detect<cr>

" Set some nice character listings, then activate list
set list listchars=tab:⟶\ ,trail:·,extends:>,precedes:<
set list

" Show matching [] and {}
set showmatch

" Spell check on
set spell spelllang=en_us
setlocal spell spelllang=en_us

" Toggle spelling with the F7 key
nmap <silent> <F7> :setlocal spell! spelllang=en_us<cr>

" Spelling
highlight clear SpellBad
highlight SpellBad term=standout ctermfg=1 term=underline cterm=underline
highlight clear SpellCap
highlight SpellCap term=underline cterm=underline
highlight clear SpellRare
highlight SpellRare term=underline cterm=underline
highlight clear SpellLocal
highlight SpellLocal term=underline cterm=underline

" where it should get the dictionary files
let g:spellfile_URL = 'http://ftp.vim.org/vim/runtime/spell'

" Set title of window to file name
set title

" Toggle paste
set pastetoggle=<F2>

" Set shell to zsh
set shell=/bin/zsh

" NERDTree shortcut
nmap <silent> <C-D> :NERDTreeToggle<CR>

" Syntastic
let g:syntastic_python_checkers = ['pylint']
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map={ 'mode': 'active',
                     \ 'active_filetypes': [],
                     \ 'passive_filetypes': ['html'] }

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" Pymode
let g:pymode_lint_ignore = "E501"
let g:pymode_rope = 0
let g:pymode_rope_completion = 0
let g:pymode_rope_complete_on_dot = 0
let g:pymode_folding = 0

" Syntax highlighting
syntax enable
syntax on

" Disable bell banners
set noerrorbells novisualbell t_vb=

" Powerline
set laststatus=2
let g:airline_powerline_fonts = 1

let g:used_javascript_libs = 'underscore,angularjs'


let g:pymode_folding = 0
