# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="gnzh"

## oh-my-zsh configuration
COMPLETION_WAITING_DOTS="true"

# Plug-ins
plugins=(git)
plugins=(vagrant)

# User configuration

source $ZSH/oh-my-zsh.sh
alias co="git checkout"
alias cob="git checkout -b"
alias cm="git commit -m"
alias pull="git pull"
alias push="git push"
alias dif="git difftool --tool=opendiff -d"
alias cleanup-branches="git branch -d $(git branch --merged | grep -v master | grep -v '^\*')"

# Load OS specific environments
if [[ "$OSTYPE" == "darwin" ]]; then
    source $HOME/.config/env/osx.env
fi

source $HOME/.config/env/dyn.env
source $HOME/.config/env/common.env

eval "$(rbenv init -)"
