# Shell config strategy
# ──────────────────────────────────────────────────────────────────────────────
# ~/.zshrc        stow-managed (toolbox/dot/zsh/.zshrc) — portable across all
#                 machines, committed to git, works with or without nix.
#
# ~/.zshrc.local  generated here by home-manager — nix-only additions sourced
#                 at the end of .zshrc. On non-nix machines the file doesn't
#                 exist and the source line in .zshrc is a no-op.
#
# ~/.zshenv       stow-managed (toolbox/dot/zsh/.zshenv) — puts Homebrew on PATH
#                 for *every* zsh, not just login shells. Homebrew's own
#                 ~/.zprofile hook is login-only, so `ssh <host> '<cmd>'` could
#                 not find `just` / `op`. See that file's header for detail.
#
# Stow + oh-my-zsh plugin/theme wiring run automatically on each deploy via
# home.activation.stowDotfiles. On the first run of a fresh machine, if
# ~/.zshrc already exists as a plain file stow will warn — back it up and
# re-run darwin-rebuild switch.
#
# Non-nix machines: install powerlevel10k once with:
#   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
#     ~/.oh-my-zsh/custom/themes/powerlevel10k
#
# THIS MODULE OWNS ALL SHELL INTEGRATION.
# home-manager's per-tool `enableZshIntegration` / `shellWrapperName` /
# `defaultOptions` options write into `programs.zsh.*` and `home.sessionVariables`,
# and BOTH are dead ends here: we don't set `programs.zsh.enable` in home-manager
# (zsh is stow-managed, above), and nothing sources hm-session-vars.sh. Those
# options render no file and change no behavior. So each tool module installs its
# binary and writes its own config file (atuin's config.toml, direnv's
# direnv.toml, yazi's yazi.toml), and every shell hook, alias, wrapper function,
# and exported variable lives here in .zshrc.local. Do not add integration flags
# back to the tool modules — they will silently do nothing.
# ──────────────────────────────────────────────────────────────────────────────
{
  lib,
  pkgs,
  osConfig ? null,
  ...
}: {
  # zsh plugins/theme as nix packages.
  # p10k is symlinked into oh-my-zsh custom themes (activation script below).
  # zsh-syntax-highlighting is sourced directly in .zshrc.local (naming mismatch
  # with oh-my-zsh's .plugin.zsh convention makes the plugin loader unreliable).
  home.packages = with pkgs; [
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-powerlevel10k
    gitstatus # provides gitstatusd; the nix zsh-powerlevel10k pkg ships an empty usrbin/
  ];

  home.activation.stowDotfiles = lib.hm.dag.entryAfter ["writeBoundary"] ''
    DOTFILES="$HOME/Git/toolbox/dot"

    # Call stow by its absolute nix path. home-manager activation runs with a
    # minimal PATH that excludes the system profile (/run/current-system/sw/bin),
    # so a bare `stow` silently no-ops on NixOS — which is why mines ended up with
    # no ~/.zshrc / ~/.tmux.conf (and thus a bare prompt). The old /opt/homebrew/bin
    # PATH hack only rescued Darwin. ${pkgs.stow}/bin/stow works everywhere.
    if [ -d "$DOTFILES" ]; then
      cd "$DOTFILES"
      for pkg in zsh aerospace tmux; do
        ${pkgs.stow}/bin/stow -v -t "$HOME" "$pkg" 2>&1 \
          || echo "stow: conflict for $pkg — backup conflicting dotfiles in ~ then re-run home-manager"
      done
    fi

    # Bootstrap oh-my-zsh if not already installed.
    # Check for oh-my-zsh.sh (not just the directory) since the p10k step below
    # may have already created ~/.oh-my-zsh/custom/.
    if [ ! -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ]; then
      ${pkgs.git}/bin/git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh.tmp"
      # Merge into existing directory to preserve custom/ themes/plugins
      cp -rn "$HOME/.oh-my-zsh.tmp/." "$HOME/.oh-my-zsh/"
      rm -rf "$HOME/.oh-my-zsh.tmp"
    fi

    # Wire nix-managed plugins/themes into oh-my-zsh's custom directory.
    OMZ_CUSTOM="''${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
    mkdir -p "$OMZ_CUSTOM/themes" "$OMZ_CUSTOM/plugins"

    # powerlevel10k theme — resolves ZSH_THEME="powerlevel10k/powerlevel10k"
    ln -sfn "${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k" \
      "$OMZ_CUSTOM/themes/powerlevel10k"

    # zsh-autosuggestions plugin — loaded by oh-my-zsh plugin list in .zshrc
    ln -sfn "${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions" \
      "$OMZ_CUSTOM/plugins/zsh-autosuggestions"
  '';

  home.file.".zshrc.local".text = ''
    # Generated by nix — do not edit manually.
    # Edit: toolbox/nixos/modules/programs/tui/zsh/default.nix

    # ── powerlevel10k gitstatus daemon ────────────────────────────────
    # The nix zsh-powerlevel10k package ships an empty gitstatus/usrbin/, so p10k
    # can't find gitstatusd and prints "gitstatus failed to initialize" (degraded
    # prompt) on headless boxes with no ~/.cache/gitstatus download fallback.
    # Point it at the gitstatusd from the standalone gitstatus package.
    export GITSTATUS_DAEMON="${pkgs.gitstatus}/bin/gitstatusd"

    # ── zsh-syntax-highlighting ───────────────────────────────────────
    # Sourced directly (bypasses oh-my-zsh plugin loader naming convention)
    source ${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

    # ── Nix-managed tool initialization ──────────────────────────────
    # zoxide — smart directory jumping (z <partial-path>)
    if command -v zoxide &>/dev/null; then
      eval "$(zoxide init zsh --cmd z)"
    fi

    # atuin — shell history search (ctrl+r / up arrow)
    if command -v atuin &>/dev/null; then
      eval "$(atuin init zsh)"
    fi

    # eza — modern ls replacement
    if command -v eza &>/dev/null; then
      alias ls='eza --group-directories-first --header --icons --group'
      alias ll='eza -l --group-directories-first --header --icons --group'
      alias la='eza -a --group-directories-first --header --icons --group'
      alias lt='eza --tree --group-directories-first --header --icons --group'
      alias lla='eza -la --group-directories-first --header --icons --group'
    fi

    # fzf — ctrl+t (paste files), ctrl+r (history), alt+c (cd)
    # The palette is hand-tuned and does NOT track stylix; unifying terminal
    # theming is a separate change.
    if command -v fzf &>/dev/null; then
      export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
      export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --inline-info --color=fg:#d0d0d0,bg:#121212,hl:#5f87af --color=fg+:#d0d0d0,bg+:#262626,hl+:#5fd7ff --color=info:#afaf87,prompt:#d7005f,pointer:#af5fff --color=marker:#87ff00,spinner:#af5fff,header:#87afaf'
      eval "$(fzf --zsh)"
    fi

    # yazi — `y` opens the file manager and cds to wherever you ended up
    if command -v yazi &>/dev/null; then
      function y() {
        local tmp cwd
        tmp="$(mktemp -t yazi-cwd.XXXXX)"
        command yazi "$@" --cwd-file="$tmp"
        if cwd="$(<"$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
          builtin cd -- "$cwd"
        fi
        rm -f -- "$tmp"
      }
    fi

    # ── Nix maintenance ──────────────────────────────────────────────
    alias ncg='nix-collect-garbage --delete-older-than 3d && sudo nix-collect-garbage -d'
    alias nc='nix flake check'
    alias cleanup='nh clean all'
    alias cs='sudo nix-store --gc'
    alias opts='man home-configuration.nix'
    ${lib.optionalString (osConfig.custom.desktop.enable or false) ''

      # ── macOS clipboard parity (GUI Linux hosts only) ────────────────
      # xclip is installed on desktop hosts via modules/home/default.nix.
      # Not added on Darwin (native pbcopy/pbpaste) or headless Linux (no xclip).
      alias pbcopy='xclip -selection clipboard'
      alias pbpaste='xclip -selection clipboard -o'
    ''}
  '';
}
