# Shell config strategy
# ──────────────────────────────────────────────────────────────────────────────
# ~/.zshrc        stow-managed (toolbox/dot/zsh/.zshrc) — portable across all
#                 machines, committed to git, works with or without nix.
#
# ~/.zshrc.local  generated here by home-manager — nix-only additions sourced
#                 at the end of .zshrc. On non-nix machines the file doesn't
#                 exist and the source line in .zshrc is a no-op.
#
# Stow + oh-my-zsh plugin/theme wiring run automatically on each deploy via
# home.activation.stowDotfiles. On the first run of a fresh machine, if
# ~/.zshrc already exists as a plain file stow will warn — back it up and
# re-run darwin-rebuild switch.
#
# Non-nix machines: install powerlevel10k once with:
#   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
#     ~/.oh-my-zsh/custom/themes/powerlevel10k
# ──────────────────────────────────────────────────────────────────────────────
{
  lib,
  pkgs,
  ...
}: {
  # zsh plugins/theme as nix packages.
  # p10k is symlinked into oh-my-zsh custom themes (activation script below).
  # zsh-syntax-highlighting is sourced directly in .zshrc.local (naming mismatch
  # with oh-my-zsh's .plugin.zsh convention makes the plugin loader unreliable).
  home.packages = with pkgs; [
    zsh-syntax-highlighting
    zsh-powerlevel10k
  ];

  home.activation.stowDotfiles = lib.hm.dag.entryAfter ["writeBoundary"] ''
    export PATH="/opt/homebrew/bin:$PATH"
    DOTFILES="$HOME/Git/toolbox/dot"

    if [ -d "$DOTFILES" ] && command -v stow &>/dev/null; then
      cd "$DOTFILES"
      stow -v -t "$HOME" zsh 2>&1 \
        || echo "stow: conflict — backup conflicting dotfiles in ~ then re-run darwin-rebuild switch"
    fi

    # Wire powerlevel10k from the nix store into oh-my-zsh's custom themes dir.
    # This is what ZSH_THEME="powerlevel10k/powerlevel10k" in .zshrc resolves to.
    OMZ_CUSTOM="''${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
    mkdir -p "$OMZ_CUSTOM/themes"
    ln -sfn "${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k" \
      "$OMZ_CUSTOM/themes/powerlevel10k"
  '';

  home.file.".zshrc.local".text = ''
    # Generated by nix — do not edit manually.
    # Edit: toolbox/nixos/modules/programs/tui/zsh/default.nix

    # ── zsh-syntax-highlighting ───────────────────────────────────────
    # Sourced directly (bypasses oh-my-zsh plugin loader naming convention)
    source ${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

    # ── Nix-managed tool initialization ──────────────────────────────
    # zoxide — smart directory jumping (z <partial-path>)
    if command -v zoxide &>/dev/null; then
      eval "$(zoxide init zsh --cmd z)"
    fi

    # atuin — shell history search (ctrl+r / up arrow)
    if command -v atuin &>/dev/null; then
      eval "$(atuin init zsh)"
    fi

    # eza — modern ls replacement
    if command -v eza &>/dev/null; then
      alias ls='eza --group-directories-first --header --icons --group'
      alias ll='eza -l --group-directories-first --header --icons --group'
      alias la='eza -a --group-directories-first --header --icons --group'
      alias lt='eza --tree --group-directories-first --header --icons --group'
      alias lla='eza -la --group-directories-first --header --icons --group'
    fi

    # ── Nix maintenance ──────────────────────────────────────────────
    alias ncg='nix-collect-garbage --delete-older-than 3d && sudo nix-collect-garbage -d'
    alias nc='nix flake check'
    alias cleanup='nh clean all'
    alias cs='sudo nix-store --gc'
    alias opts='man home-configuration.nix'
  '';
}
