# Shell config strategy
# ──────────────────────────────────────────────────────────────────────────────
# ~/.zshrc        stow-managed (toolbox/dot/zsh/.zshrc) — portable across all
#                 machines, committed to git, works with or without nix.
#
# ~/.zshrc.local  generated here by home-manager — nix-only additions that are
#                 sourced at the end of .zshrc. Not committed to git. On non-nix
#                 machines the file simply doesn't exist and the source is a no-op.
#
# Stow is run automatically on each deploy via home.activation.stowDotfiles.
# On first run, if ~/.zshrc exists as a plain file, stow will warn — back it
# up manually and re-run darwin-rebuild switch.
# ──────────────────────────────────────────────────────────────────────────────
{lib, ...}: {
  # Run stow for the zsh dotfiles after each home-manager activation.
  home.activation.stowDotfiles = lib.hm.dag.entryAfter ["writeBoundary"] ''
    export PATH="/opt/homebrew/bin:$PATH"
    DOTFILES="$HOME/Git/toolbox/dot"

    if [ -d "$DOTFILES" ] && command -v stow &>/dev/null; then
      cd "$DOTFILES"
      stow -v -t "$HOME" zsh 2>&1 \
        || echo "stow: conflict — backup conflicting dotfiles in ~ then re-run darwin-rebuild switch"
    fi

    # Install oh-my-zsh extras that aren't bundled with omz itself
    if command -v git &>/dev/null; then
      P10K_DIR="$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
      [ ! -d "$P10K_DIR" ] && \
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$P10K_DIR" || true

      ZSH_SYNTAX_DIR="$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      [ ! -d "$ZSH_SYNTAX_DIR" ] && \
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_SYNTAX_DIR" || true
    fi
  '';

  home.file.".zshrc.local".text = ''
    # Generated by nix-darwin — do not edit manually.
    # Edit: toolbox/nixos/modules/programs/tui/zsh/default.nix

    # ── Nix-managed tool initialization ──────────────────────────────
    # These tools are installed by nix; their shell hooks live here so
    # stow/.zshrc stays portable on non-nix machines.

    # zoxide — smart directory jumping (z <partial-path>)
    if command -v zoxide &>/dev/null; then
      eval "$(zoxide init zsh --cmd z)"
    fi

    # atuin — shell history search (ctrl+r / up arrow)
    if command -v atuin &>/dev/null; then
      eval "$(atuin init zsh)"
    fi

    # eza — modern ls replacement (aliases set to match eza extra options)
    if command -v eza &>/dev/null; then
      alias ls='eza --group-directories-first --header --icons --group'
      alias ll='eza -l --group-directories-first --header --icons --group'
      alias la='eza -a --group-directories-first --header --icons --group'
      alias lt='eza --tree --group-directories-first --header --icons --group'
      alias lla='eza -la --group-directories-first --header --icons --group'
    fi

    # ── Nix maintenance ──────────────────────────────────────────────
    alias ncg='nix-collect-garbage --delete-older-than 3d && sudo nix-collect-garbage -d'
    alias nc='nix flake check'
    alias cleanup='nh clean all'
    alias cs='sudo nix-store --gc'
    alias opts='man home-configuration.nix'
  '';
}
