# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Auto-correction
ENABLE_CORRECTION="true"
# Glob pattern of words to skip correction for; extend with (pi|other|words).
# CORRECT_IGNORE covers command-word correction (`correct`); CORRECT_IGNORE_ALL
# covers `correct_all` (every word), which is what ENABLE_CORRECTION turns on —
# without the _ALL variant, `claude` still gets "corrected" to a nearby .claude dir.
CORRECT_IGNORE="(pi|claude)"
CORRECT_IGNORE_ALL="(pi|claude)"

# Show dots while waiting for completion
COMPLETION_WAITING_DOTS="true"

# History settings
# https://unix.stackexchange.com/a/273863/180341
HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

# Plugins
plugins=(git
  docker
  colored-man-pages
  colorize
  github
  virtualenv
  pip
  python
  brew
  macos
  # zsh-syntax-highlighting: sourced directly in ~/.zshrc.local on nix machines
  # (nix pkg uses .zsh not .plugin.zsh, so oh-my-zsh plugin loader can't find it)
  zsh-autosuggestions
  web-search
  jsontools
  # dotenv: intentionally NOT loaded. It auto-sources a repo's .env on `cd` and
  # exports it, which shadows tool-loaded .env files (Next.js .env.local, Vite,
  # python-dotenv, `docker --env-file`) since shell env wins. Use direnv (.envrc)
  # per-project for opt-in, auto-unloading dir env instead.
)

source $ZSH/oh-my-zsh.sh

# VS Code shell integration (remote SSH and native terminal)
if [[ -n "$VSCODE_IPC_HOOK_CLI" ]] || [[ "$TERM_PROGRAM" == "vscode" ]]; then
  if command -v code &>/dev/null; then
    . "$(code --locate-shell-integration-path zsh 2>/dev/null)" 2>/dev/null || true
  fi
fi

# ── Environment ──────────────────────────────────────────────────────

HOSTNAME=$(hostname)

# Toolbox
TOOLBOX_HOME=~/Git/toolbox
export TOOLBOX_HOME=$TOOLBOX_HOME
# Add bin/ and all subdirectories recursively to PATH
path+=($TOOLBOX_HOME/bin $TOOLBOX_HOME/bin/**/*(/N))

# Load toolbox secrets (generated by `just secrets` from 1Password)
# set -a auto-exports every variable so child processes (uv run, python, etc.) inherit them
if [[ -f "$TOOLBOX_HOME/nixos/secrets/.env" ]]; then
  set -a
  source "$TOOLBOX_HOME/nixos/secrets/.env"
  set +a
fi

# Editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# Displays which virtual environment you're working on
export VIRTUAL_ENV_DISABLE_PROMPT=

# ── PATH additions ──────────────────────────────────────────────────

export PATH="$PATH:$HOME/.local/bin"
export PATH="$HOME/Apps:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
# Also try brew-installed nvm (macOS)
if command -v brew &>/dev/null && [ -s "$(brew --prefix nvm)/nvm.sh" ]; then
  source "$(brew --prefix nvm)/nvm.sh"
fi

# Go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$GOPATH/bin

# Poetry
export PATH="$PATH:$HOME/.poetry/bin"
export PATH="$PATH:$HOME/.local/share/pypoetry/venv/bin"

# pyenv
if command -v pyenv >/dev/null 2>&1; then
    export PYENV_ROOT="$HOME/.pyenv"
    if [[ ":$PATH:" != *":$PYENV_ROOT/bin:"* ]]; then
        export PATH="$PYENV_ROOT/bin:$PATH"
    fi
    eval "$(pyenv init --path)"
    if command -v pyenv virtualenv-init >/dev/null 2>&1; then
        eval "$(pyenv virtualenv-init -)"
    fi
fi

# direnv
if command -v direnv &>/dev/null; then
  eval "$(direnv hook zsh)"
fi

# uv / rustup — added by their installers, loads cargo/uv onto PATH
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# cargo install binaries (Homebrew Rust doesn't add this automatically)
export PATH="$HOME/.cargo/bin:$PATH"

# libpq (Postgres CLI tools)
if [ -d "/opt/homebrew/opt/libpq/bin" ]; then
  export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
fi

# LM Studio CLI
if [ -d "$HOME/.lmstudio/bin" ]; then
  export PATH="$PATH:$HOME/.lmstudio/bin"
fi

# Screenlayout (xrandr scripts on Linux)
if [ -d "$HOME/.screenlayout" ]; then
  export PATH="$HOME/.screenlayout:$PATH"
fi

# ── Aliases ──────────────────────────────────────────────────────────

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias e="exit"
alias c="clear"
alias lg="lazygit"
alias cat="bat"
alias htop="btop"
alias python='/usr/bin/python3'
alias audio="pavucontrol"

# Clipboard (pbcopy on macOS, xclip on Linux)
if [[ "$OSTYPE" == "darwin"* ]]; then
  alias clip="pbcopy <"
else
  alias clip="xclip -sel clip <"
fi

# ── Script aliases ───────────────────────────────────────────────────
# All scripts live in $TOOLBOX_HOME/bin (on PATH). These are convenience aliases.

alias git-all-history="git-all-history.sh"
alias git-commit-undo="git-commit-undo.sh"
alias youtube-to-audio="youtube-to-audio.sh"
alias search-string="search-string.sh"
alias search-file="search-file.sh"
alias docker-clear-containers="docker-clear-containers.sh"
alias docker-clear-images="docker-clear-images.sh"
alias docker-clear-volumes="docker-clear-volumes.sh"
alias docker-clear-networks="docker-clear-networks.sh"
alias localclaude="localclaude.sh"
alias difit="difit.sh"
alias gpr="git-pr.sh"

# Claude Code in Docker with persistent auth and session history
# Uses a named Docker volume (claude-code-config) to persist ~/.claude across runs
# Automatically creates volume and builds image on first run (idempotent)
# Based on: https://code.claude.com/docs/en/devcontainer
# Reference: https://github.com/anthropics/claude-code/tree/main/.devcontainer
unalias claude-docker 2>/dev/null || true
claude-docker() {
  local image_name="my-claude-code:latest"
  local dockerfile_dir="$TOOLBOX_HOME/claude-code"
  local host_uid=$(id -u)
  local host_gid=$(id -g)

  # Build image if it doesn't exist
  if ! docker image ls | grep -q "$image_name"; then
    echo "Building Docker image: $image_name"
    docker build -t "$image_name" "$dockerfile_dir" || return 1
  fi

  # Claude Code encodes the working directory path into project identifiers.
  # To share sessions between host and container, they must see the SAME absolute path.
  # Mount ~/Git at its actual host location instead of /workspace so paths match.
  local host_pwd="$PWD"
  local git_home="$(cd "$HOME/Git" 2>/dev/null && pwd)"

  # Run Claude Code in container with shared history and host user
  # -v ~/.claude:/home/node/.claude: Bind mount host's ~/.claude (shared session history)
  # -v $git_home:$git_home: Mount ~/Git at its actual absolute path (preserves project ID)
  # -w $host_pwd: Set same working directory as host (ensures same project in Claude)
  # -u host_uid:host_gid: Run as host user (files created are owned by you)
  # -e HOME=/home/node: Set home directory (required when running with custom UID)
  docker run --rm -it \
    -v ~/.claude:/home/node/.claude \
    -v "$git_home:$git_home" \
    -w "$host_pwd" \
    -u "$host_uid:$host_gid" \
    -e HOME=/home/node \
    -e CLAUDE_CONFIG_DIR=/home/node/.claude \
    "$image_name" \
    code --dangerously-skip-permissions "$@"
}

# ── GitHub CLI ───────────────────────────────────────────────────────

alias ghpr="gh pr view --web"
alias ghprc="gh pr create --web"
alias ghprl="gh pr list"
alias ghis="gh issue view --web"
alias ghisc="gh issue create --web"
alias ghisl="gh issue list"
alias ghrepo="gh repo view --web"

# ── Git ──────────────────────────────────────────────────────────────

alias gdiff="git diff"
alias gshow="git show --ext-diff"
alias glog="git log --ext-diff -p"
alias dhtml="git diff --no-ext-diff HEAD | diff2html -i stdin"
alias dhtmls="git diff --no-ext-diff --cached | diff2html -i stdin"        # staged only
alias dhtmlside="git diff --no-ext-diff HEAD | diff2html -s side -i stdin" # side-by-side

# Capture the output of a command so it can be retrieved with ret
# https://stackoverflow.com/a/58598185/1983957
cap() {
    tee /tmp/capture.out
}

# Return the output of the most recent command that was captured by cap
ret() {
    command cat /tmp/capture.out
}

# ── Completions ──────────────────────────────────────────────────────

autoload bashcompinit && bashcompinit

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ngrok
# NOTE: do NOT `eval "$(ngrok completion)"` at interactive startup. A wedged
# ngrok binary (seen on dungeon) makes that call block forever, which hangs the
# whole shell mid-init so the prompt never finishes rendering. The completion is
# a nice-to-have; if you want it back, generate it once to a file and source
# that instead of invoking ngrok on every shell launch:
#   ngrok completion zsh > ~/.cache/ngrok-completion.zsh   # run manually, once
[ -f ~/.cache/ngrok-completion.zsh ] && source ~/.cache/ngrok-completion.zsh

# ── Powerlevel10k ────────────────────────────────────────────────────

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# ── Machine-local ────────────────────────────────────────────────────
# ~/.zshrc.local is generated by nix (nixos/modules/programs/tui/zsh/default.nix)
# and sourced here for nix-only additions. Safe no-op on non-nix machines.
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
