# nixos/modules/programs/tui/tmux/default.nix
#
# tmux config lives in the PORTABLE stow file dot/tmux/.tmux.conf (deployed to
# ~/.tmux.conf by the stowDotfiles activation in ../zsh/default.nix on nix hosts,
# and by `just stow tmux` on non-nix hosts). This module supplies ONLY the
# nix-only overlay that the portable config sources via
# `source-file -q ~/.tmux.local.conf`.
#
# Why an overlay instead of programs.tmux: it keeps a single portable source of
# truth and avoids a second generated ~/.config/tmux/tmux.conf, which tmux would
# ALSO load (Homebrew tmux loads every file in its search list) and which would
# silently conflict with the stow config.
_: {
  home.file.".tmux.local.conf".text = ''
    # Generated by nix — do not edit manually.
    # Edit: toolbox/nixos/modules/programs/tui/tmux/default.nix

    # Pin tmux's shell to zsh so starship/zoxide/fzf/eza work inside tmux panes
    # (fixes the regression from commit 815d257). Use the STABLE profile symlink,
    # NOT ''${pkgs.zsh}/bin/zsh: /run/current-system/sw/bin/zsh is a GC-root that
    # atomically updates each activation, so a long-running tmux server never
    # ends up exec'ing a garbage-collected /nix/store path.
    set -g default-shell "/run/current-system/sw/bin/zsh"
  '';
}
