# Generated by `just secrets` via 1Password CLI (`op inject`).
# Do not edit — update values in 1Password, then re-run `just secrets`.

OMLX_API_KEY={{ op://Infra/oMLX/api_key }}
# rohan only: `just secrets` strips it elsewhere.
LITELLM_API_KEY={{ op://Infra/LiteLLM/master_key }}
DEEPSEEK_API_KEY={{ op://Infra/DeepSeek/api_key }}
PUSHOVER_USER_KEY={{ op://Infra/Pushover/user_key }}
PUSHOVER_WORK_API_KEY={{ op://Infra/Pushover/work_api_key }}
# The Hermes bot account's app password; mail-ip.py --from must match.
FROM_EMAIL_ADDRESS_PASSWORD="{{ op://Infra/Hermes/gmail_app_password }}"

# No chat tokens: every shell exports this.
