- name: Deploy Toolbox
  hosts: "localhost"

  tasks:
    - name: Include variables from variables/ubuntu.yml
      ansible.builtin.include_vars:
        file: ../variables/ubuntu.yml

- import_playbook: install-brew-packages.yml
- import_playbook: set-zsh-as-default-shell.yml
- import_playbook: symlink-dot-files.yml
- import_playbook: oh-my-zsh.yml
