- hosts: "localhost"
  tasks:
    - name: Install Flatpak
      package:
        name: flatpak
        state: present

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install Slack from Flathub
      flatpak:
        name: com.slack.Slack
        state: present
        method: user

    - name: Install Spotify from Flathub
      flatpak:
        name: com.spotify.Client
        state: present
        method: user

    - name: Install Bitwarden from Flathub
      flatpak:
        name: com.bitwarden.desktop
        state: present
        method: user

    - name: Install Obsidian from Flathub
      flatpak:
        name: com.obsidian.Obsidian
        state: present
        method: user

    - name: Install Visual Studio Code from Flathub
      flatpak:
        name: com.visualsutdio.code
        state: present
        method: user