---
- name: configure sudo
  hosts: all
  tasks:
  - name: install sudo
    apt:
     name: sudo
     state: present
    become: true
  - name: add group
    become: true
    group:
      name: sudo_nopasswd
      state: present
  - name: add line to sudoers
    become: true
    lineinfile:
     dest: /etc/sudoers
     state: present
     regexp: "sudo_nopasswd"
     line: "%sudo_nopasswd ALL=(ALL) NOPASSWD: ALL"
     # validate: "visudo -cf %s"