- name: Oh My ZSH
  hosts: "localhost"
  tasks:
    - name: Install Oh My Zsh # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1

    - name: Install zsh-completions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
        depth: 1

    - name: Install zsh-syntax-highlighting plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        depth: 1

    - name: Install autoupdate-zsh-plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
        dest: ~/.oh-my-zsh/custom/plugins/autoupdate
        depth: 1

    - name: Install Powerline10k theme # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        depth: 1

    - name: Install Powerline fonts
      become: true
      ansible.builtin.package:
        state: present
        name: "fonts-powerline"
      register: package_result
      notify: fonts_installed

  handlers:
    - name: Remind user to leverage Powerline fonts
      listen: fonts_installed
      ansible.builtin.debug:
        msg: "I've just installed powerline fonts. Configure your terminal to take advantage of this new font."
