- name: ZSH
  hosts: "localhost"
  become: true
  tasks:
    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ target_username }}"
        shell: /bin/zsh
