- name: Symlink Dot Files
  hosts: "localhost"
  tasks:
    - name: Prepare nvim directory
      ansible.builtin.file:
        path: ~/.config/nvim
        state: directory

    - name: Copy nvim dotfile
      ansible.builtin.file:
        src: ../../dot/
        dest: 
        state: link