- name: Symlink Dot Files
  hosts: "localhost"
  tasks:
    - name: Prepare nvim directory
      ansible.builtin.file:
        path: ~/.config/nvim
        state: directory
        mode: "0644"

    - name: Copy nvim dotfile
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../dot/config/nvim/init.vim"
        dest: ~/.config/nvim/init.vim
        state: link
