# Deploy to a specific host
# Usage: $ deploy host <host name>
deploy host:
  sudo nixos-rebuild switch --flake .#{{host}}

# Debug deployment to a specific host
# Usage: $ debug host <host name>
debug host:
  sudo nixos-rebuild switch --flake .#{{host}} --show-trace --verbose

# List available hosts (assuming they're in the hosts directory)
list-hosts:
  @ls hosts/

# List past NixOS generations
list-generations:
  sudo nix-env --list-generations --profile /nix/var/nix/profiles/system

# Delete specific generations
delete-specific-generations generations:
  nix-collect-garbage --delete-generations #{{generations}}

# Delete all old generations. Can remove sudo to remove not remove system packages
delete-all-old-generations:
  sudo nix-collect-garbage --delete-old

up:
  nix flake update

# Update specific input
# usage: make upp i=home-manager
upp:
  nix flake update $(i)

history:
  sudo nix profile history --profile /nix/var/nix/profiles/system

repl:
  nix repl -f flake:nixpkgs

clean:
  # remove all generations older than 7 days
  sudo nix profile wipe-history --profile /nix/var/nix/profiles/system  --older-than 7d

gc:
  # garbage collect all unused nix store entries
  sudo nix-collect-garbage --delete-old
