set shell := ["zsh", "-cu"]
flake_path := "~/Git/toolbox"

# Deploy to a specific host
# Usage: $ just deploy host <host name>
deploy host:
  sudo nixos-rebuild switch --flake .#{{host}}

# Upgrade a specific host
# Usage: $ just deploy host <host name>
upgrade host:
  sudo nixos-rebuild --upgrade switch --flake .#{{host}}

# Debug deployment to a specific host
# Usage: $ just debug host <host name>
debug host:
  sudo nixos-rebuild switch --flake .#{{host}} --show-trace --verbose

# List available hosts (assuming they're in the hosts directory)
list-hosts:
  @ls hosts/

# List past NixOS generations
list-generations:
  sudo nix-env --list-generations --profile /nix/var/nix/profiles/system

# Delete specific generations
delete-specific-generations generations:
  nix-collect-garbage --delete-generations #{{generations}}

# Delete all old generations. Can remove sudo to remove not remove system packages
delete-all-old-generations:
  sudo nix-collect-garbage --delete-old

up:
  nix flake update

# Update specific input
# usage: make upp i=home-manager
upp:
  nix flake update $(i)

# Rebuild
# The host argument is required.
# The flake_path defaults to the `~/Git/toolbox`
# Usage: Override the path with `just fr <hostname> flake_path=.` or `just fr <hostname> flake_path=~/toolbox/nixos`
# Usage: `just fr <hostname>`
fr host: # Default to current directory
  nh os switch --hostname {{host}} {{flake_path}}

# Test rebuild
# The host argument is required.
# The flake_path defaults to `~/Git/toolbox`
# Usage: `just ft <hostname>`
ft host: # Default to current directory
  nh os test --hostname {{host}} {{flake_path}}

# Update and Rebuild Flake
# Usage: `just fu <hostname>` flake_path defaults to the cwd
fu host:
    nh os switch --hostname {{host}} --update {{flake_path}}

history:
  sudo nix profile history --profile /nix/var/nix/profiles/system

repl:
  nix repl -f flake:nixpkgs

clean:
  # remove all generations older than 7 days
  sudo nix profile wipe-history --profile /nix/var/nix/profiles/system  --older-than 7d

gc:
  # garbage collect all unused nix store entries
  sudo nix-collect-garbage --delete-old
